FROM node:22-bookworm

WORKDIR /app

RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    rm -rf /var/lib/apt/lists/*

COPY . .

RUN chmod +x stockfish/stockfish-linux/stockfish-linux-x86-64-universal

RUN javac getPuzzles.java MiddleLayer.java StockfishEng.java

RUN npm install

CMD ["node", "server.js"]